name: build-and-test
on:
  push:
    branches: [ main ]
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'
  pull_request:
env:
  TEST_RESULTS: testbed/tests/results/junit/results.xml

jobs:
  setup-environment:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17
      - name: Cache Go
        id: go-cache
        uses: actions/cache@v3
        with:
          path: |
            ~/go/bin
            ~/go/pkg/mod
          key: go-cache-${{ runner.os }}-${{ hashFiles('**/go.sum') }}
      - name: Install dependencies
        if: steps.go-cache.outputs.cache-hit != 'true'
        run: echo "done"
      - name: Install Tools
        if: steps.go-cache.outputs.cache-hit != 'true'
        run: echo "done"
  check-collector-module-version:
    runs-on: ubuntu-latest
    needs: [setup-environment]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Check Collector Module Version
        run: echo "done"
  check-codeowners:
    runs-on: ubuntu-latest
    needs: [setup-environment]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Check Code Owner Existence
        run: echo "done"
      - name: Check Component Existence
        run: echo "done"
  lint-matrix:
    strategy:
      matrix:
        group:
          - receiver-0
          - receiver-1
          - processor
          - exporter
          - extension
          - internal
          - other
    runs-on: ubuntu-latest
    needs: [setup-environment]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17
      - name: Cache Go
        id: go-cache
        uses: actions/cache@v3
        with:
          path: |
            ~/go/bin
            ~/go/pkg/mod
          key: go-cache-${{ runner.os }}-${{ hashFiles('**/go.sum') }}
      - name: Install dependencies
        if: steps.go-cache.outputs.cache-hit != 'true'
        run: echo "done"
      - name: Install Tools
        if: steps.go-cache.outputs.cache-hit != 'true'
        run: echo "done"
      - name: Cache Lint Build
        uses: actions/cache@v3
        with:
          path: ~/.cache/go-build
          key: go-lint-build-${{ runner.os }}-${{ hashFiles('**/go.sum') }}
      - name: Lint
        run: echo "done"
  lint:
    runs-on: ubuntu-latest
    needs: [setup-environment, lint-matrix]
    steps:
      - name: Unit Tests Complete
        run: echo "done"
  checks:
    runs-on: ubuntu-latest
    needs: [setup-environment]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17
      - name: Cache Go
        id: go-cache
        uses: actions/cache@v3
        with:
          path: |
            ~/go/bin
            ~/go/pkg/mod
          key: go-cache-${{ runner.os }}-${{ hashFiles('**/go.sum') }}
      - name: Install dependencies
        if: steps.go-cache.outputs.cache-hit != 'true'
        run: echo "done"
      - name: Install Tools
        if: steps.go-cache.outputs.cache-hit != 'true'
        run: echo "done"
      - name: CheckDoc
        run: echo "done"
      - name: Porto
        run: |
          echo "done"
      - name: Check for go mod dependency changes
        run: |
          echo "done"
      - name: CodeGen
        run: |
          echo "done"
      - name: MultimodVerify
        run: echo "done"
  unittest-matrix:
    strategy:
      matrix:
        go-version: [1.18, 1.17]
        group:
          - receiver-0
          - receiver-1
          - processor
          - exporter
          - extension
          - internal
          - other
    runs-on: ubuntu-latest
    needs: [setup-environment]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - name: Cache Go
        id: go-cache
        uses: actions/cache@v3
        with:
          path: |
            ~/go/bin
            ~/go/pkg/mod
          key: go-cache-${{ runner.os }}-${{ hashFiles('**/go.sum') }}
      - name: Install dependencies
        if: steps.go-cache.outputs.cache-hit != 'true'
        run: echo "done"
      - name: Install Tools
        if: steps.go-cache.outputs.cache-hit != 'true'
        run: echo "done"
      - name: Cache Test Build
        uses: actions/cache@v3
        with:
          path: ~/.cache/go-build
          key: go-test-build-${{ runner.os }}-${{ matrix.go-version }}-${{ hashFiles('**/go.sum') }}
      - name: Run Unit Tests
        run: echo "done"
  unittest:
    strategy:
      matrix:
        go-version: [1.18, 1.17]
    runs-on: ubuntu-latest
    needs: [setup-environment, unittest-matrix]
    steps:
      - name: Unit Tests Complete
        run: echo "done"

  integration-tests:
    runs-on: ubuntu-latest
    needs: [setup-environment]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17
      - name: Cache Go
        id: go-cache
        uses: actions/cache@v3
        with:
          path: |
            ~/go/bin
            ~/go/pkg/mod
          key: go-cache-${{ runner.os }}-${{ hashFiles('**/go.sum') }}
      - name: Run Integration Tests
        run: echo "done"

  correctness-traces:
    runs-on: ubuntu-latest
    needs: [setup-environment]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17
      - name: Cache Go
        id: go-cache
        uses: actions/cache@v3
        with:
          path: |
            ~/go/bin
            ~/go/pkg/mod
          key: go-cache-${{ runner.os }}-${{ hashFiles('**/go.sum') }}
      - name: Install dependencies
        if: steps.go-cache.outputs.cache-hit != 'true'
        run: echo "done"
      - name: Install Tools
        if: steps.go-cache.outputs.cache-hit != 'true'
        run: echo "done"
      - name: Correctness
        run: echo "done"
  correctness-metrics:
    runs-on: ubuntu-latest
    needs: [setup-environment]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17
      - name: Cache Go
        id: go-cache
        uses: actions/cache@v3
        with:
          path: |
            ~/go/bin
            ~/go/pkg/mod
          key: go-cache-${{ runner.os }}-${{ hashFiles('**/go.sum') }}
      - name: Install dependencies
        if: steps.go-cache.outputs.cache-hit != 'true'
        run: echo "done"
      - name: Install Tools
        if: steps.go-cache.outputs.cache-hit != 'true'
        run: echo "done"
      - name: Correctness
        run: echo "done"

  build-examples:
    runs-on: ubuntu-latest
    needs: [setup-environment]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Build Examples
        run: echo "done"

  cross-compile:
    runs-on: ubuntu-latest
    needs: [unittest, integration-tests, lint]
    strategy:
      matrix:
        binary:
          - darwin_amd64
          - darwin_arm64
          - linux_amd64
          - linux_arm64
          - windows_amd64
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17
      - name: Cache Go
        id: go-cache
        uses: actions/cache@v3
        with:
          path: |
            ~/go/bin
            ~/go/pkg/mod
          key: go-cache-${{ runner.os }}-${{ hashFiles('**/go.sum') }}
      - name: Install dependencies
        if: steps.go-cache.outputs.cache-hit != 'true'
        run: echo "done"
      - name: Install Tools
        if: steps.go-cache.outputs.cache-hit != 'true'
        run: echo "done"
      - name: Build Collector ${{ matrix.binary }}
        run: echo "done"
      - name: Upload Collector Binaries
        uses: actions/upload-artifact@v3
        with:
          name: collector-binaries
          path: ./bin/*

  build-package:
    runs-on: ubuntu-latest
    needs: [cross-compile]
    strategy:
      fail-fast: false
      matrix:
        package_type: ["deb", "rpm"]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'
      - name: Install fpm
        run: echo "done"
      - name: Download Collector Binaries
        uses: actions/download-artifact@v3
        with:
          name: collector-binaries
          path: bin/
      - run: echo "done"
      - name: Set Release Tag
        id: github_tag
        run: echo "done"
      - name: Build ${{ matrix.package_type }} amd64 package
        run: echo "done"
      - name: Build ${{ matrix.package_type }} arm64 package
        run: echo "done"
      - name: Test ${{ matrix.package_type }} package
        run: |
          echo "done"
      - name: Upload Packages
        uses: actions/upload-artifact@v3
        with:
          name: collector-packages
          path: ./dist/*
  windows-msi:
    if: false # skip. See https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/10113
    runs-on: windows-latest
    needs: [cross-compile]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Download Binaries
        uses: actions/download-artifact@v3
        with:
          name: collector-binaries
          path: ./bin/
      - name: Cache Wix
        id: wix-cache
        uses: actions/cache@v3
        with:
          path: |
            "C:\Program Files (x86)\WiX Toolset v3.11"
          key: wix-3.11
      - name: Install Wix Toolset
        if: steps.wix-cache.outputs.cache-hit != 'true'
        run: echo "done"
      - run: echo "done"
      - name: Build MSI
        run: |
          echo "done"
      - name: Validate MSI
        run: echo "done"
      - name: Upload MSI
        uses: actions/upload-artifact@v3
        with:
          name: collector-packages
          path: ./dist/*.msi

  publish-check:
    runs-on: ubuntu-latest
    needs: [build-package]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Download Binaries
        uses: actions/download-artifact@v3
        with:
          name: collector-binaries
      - name: Download Packages
        uses: actions/download-artifact@v3
        with:
          name: collector-packages
          path: ./dist/
      - name: Verify Distribution Files Exist
        id: check
        run: echo "done"
  publish-dev:
    runs-on: ubuntu-latest
    needs: [lint, unittest, integration-tests, build-package]
    if: (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v')) && github.repository == 'open-telemetry/opentelemetry-collector-contrib'
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17
      - name: Mkdir bin and dist
        run: |
          echo "done"
      - name: Cache Go
        id: go-cache
        uses: actions/cache@v3
        with:
          path: |
            ~/go/bin
            ~/go/pkg/mod
          key: go-cache-${{ runner.os }}-${{ hashFiles('**/go.sum') }}
      - name: Install dependencies
        if: steps.go-cache.outputs.cache-hit != 'true'
        run: echo "done"
      - name: Install Tools
        if: steps.go-cache.outputs.cache-hit != 'true'
        run: echo "done"
      - name: Download Binaries
        uses: actions/download-artifact@v3
        with:
          name: collector-binaries
          path: ./bin/
      - run: echo "done"
      - name: Download Packages
        uses: actions/download-artifact@v3
        with:
          name: collector-packages
          path: ./dist/
      - name: Add Permissions to Tool Binaries
        run: echo "done"
      - name: Verify Distribution Files Exist
        id: check
        run: echo "done"
      - name: Build Docker Image
        if: steps.check.outputs.passed == 'true'
        run: |
            echo "done"
      - name: Validate Docker Image
        if: steps.check.outputs.passed == 'true'
        run: |
            echo "done"
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push Docker Image
        if: steps.check.outputs.passed == 'true'
        run: |
            echo "done"
  publish-stable:
    runs-on: ubuntu-latest
    needs: [lint, unittest, integration-tests, build-package]
    if: startsWith(github.ref, 'refs/tags/v') && github.repository == 'open-telemetry/opentelemetry-collector-contrib'
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17
      - name: Mkdir bin and dist
        run: |
          echo "done"
      - name: Cache Go
        id: go-cache
        uses: actions/cache@v3
        with:
          path: |
            ~/go/bin
            ~/go/pkg/mod
          key: go-cache-${{ runner.os }}-${{ hashFiles('**/go.sum') }}
      - name: Install dependencies
        if: steps.go-cache.outputs.cache-hit != 'true'
        run: echo "done"
      - name: Install Tools
        if: steps.go-cache.outputs.cache-hit != 'true'
        run: echo "done"
      - name: Set Release Tag
        id: github_tag
        run: echo "done"
      - name: Create Github Release
        run: |
          echo "done"
